# 分表分库 Standard策略
# 配置Sharding-JDBC的分片策略
# 配置数据源，给数据源起名g1,g2...此处可配置多数据源
spring:
  shardingsphere:
    datasource:
      g0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root1234
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/good_db_1?characterEncoding=utf-8&useUnicode=true&useSSL=false&serverTimezone=UTC
        username: root
      g1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root1234
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/good_db_1?characterEncoding=utf-8&useUnicode=true&useSSL=false&serverTimezone=UTC
        username: root
      g2:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root1234
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/good_db_2?characterEncoding=utf-8&useUnicode=true&useSSL=false&serverTimezone=UTC
        username: root
      names: g0,g1,g2
    sharding:
      tables:
        goods:
          actual-data-nodes: g$->{1..2}.goods_$->{1..2}
          database-strategy:
            complex:
              sharding-columns: user_id
              algorithm-class-name: com.example.shardingjdbc.algorithm.complex.MyComplexDatabaseAlgorithm
          table-strategy:
            complex:
              sharding-columns: user_id
              algorithm-class-name: com.example.shardingjdbc.algorithm.complex.MyComplexTableAlgorithm
      default-data-source-name: g0









