
spring:
  application:
    name: kafka-server

  kafka:
    bootstrap-servers: 42.192.117.45:9092
    producer:
      retries: 3
      #procedure??leader?????????????????????????????????????????
      #acks = 0 ??????????????????????????????????????????????????????????????????????????????????????????????????????????????????-1?
      #acks = 1 ????leader?????????????????????????????????????????????leader??????????????????????????????????????
      #acks = all ????leader?????????????????????????????????????????????????????????????acks = -1????
      acks: -1
    consumer:
      group-id: TEST
      auto-offset-reset: earliest
      enable-auto-commit: false
      auto-commit-interval: 100
      max-poll-records: 5
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    ssl:
      protocol: https
server:
  port: 8888


management.endpoint.metrics.enabled: true
management.endpoints.web.exposure.include: '*'
management.endpoint.prometheus.enabled: true
management.metrics.export.prometheus.enabled: true