spring:
  datasource:
    create_database: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/liquibase?characterEncoding=utf8&useSSL=true&useUnicode=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root1234
  liquibase:
    enabled: true
    change-log: classpath:changelog-root.xml