server:
  port: 5004

spring:
  application:
    name: keep-shardingjdbc
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 42.192.117.45:8848
#        group: KEEP
#        namespace: keep
  profiles:
    active: complex
#    active: inline
#    active: hint
#    active: standard
  shardingsphere:
    enabled: true # ??sharding jdbc
spring.main.allow-bean-definition-overriding: true
spring.shardingsphere.props.sql.show: true




