server:
  port: 8080

nebula:
  ngbatis:
    session-life-length: 300000
    check-fixed-rate: 300000
    # space name needs to be informed through annotations(@Space) or xml(space="test")
    # default false(false: Session pool map will not be initialized)
    use-session-pool: false
  hosts: 127.0.0.1:9669
  username: root
  password: nebula
  space: assets_graph
  pool-config:
    min-conns-size: 4
    max-conns-size: 10
    timeout: 6000
    idle-time: 0
    interval-idle: -1
    wait-time: 6000
    min-cluster-health-rate: 1.0
    enable-ssl: false

logging:
  level:
    org.nebula.contrib: DEBUG