seata:
  application-id: keep-app
  enabled: true
  tx-service-group: my_test_tx_group #和上面的nacos的上面的配置一致
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      namespace: keep #配置上面的namespace
      serverAddr: http://127.0.0.1:8848 #nacos地址
      group: SEATA_GROUP
  registry:
    type: nacos
    nacos:
      application: serverAddr
      serverAddr: http://127.0.0.1:8848
      group: SEATA_GROUP
      namespace: keep
      cluster: default

mybatis-plus:
  mapper-locations:


