spring:
  datasource:
    mysql:
      enable: true
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/default?serverTimezone=UTC
      username: root
      password: root1234
    pgsql:
      enable: true
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://42.192.117.45:5432/default
      password: 123456
      username: postgres
    clickhouse:
      enable: true
      driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
      url: jdbc:clickhouse://42.192.117.45:8123
      username: def
      password: 123456
    oracle:
      enable: true
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521/orcl
      password: test
      username: test

mybatis-plus:
  configuration:
    # sql 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # sql 不打印sql
#    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl